---
- name: Install MySQL package
  yum: name={{ item }} enablerepo=remi state=present
  with_items:
    - mysql-server
    - MySQL-python

- name: Start MySQL Service
  service: name=mysqld state=started enabled=yes

- name: Insert iptables rule
  lineinfile: >
    dest=/etc/sysconfig/iptables
    state=present
    regexp='{{ mysql_port }}'
    insertafter='^:OUTPUT '
    line='-A INPUT -p tcp  --dport {{ mysql_port }} -j  ACCEPT'
  notify: restart iptables

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify: restart mysql
